[build]
  command = "npm run build:static"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_AMAP_SERVICE_HOST = "/api/amap"
  NEXT_PUBLIC_TRIP_API_URL = "/api/trip-data"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
